name: duyurubu
description: "Duyurubu"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.10.4
  flutter_bluetooth_serial: ^0.4.0
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  flutter_localizations:
    sdk: flutter
  translator: ^1.0.3+1
  image_picker: ^1.0.4
  file_picker: ^10.3.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: BrandonText
      fonts:
        - asset: assets/fonts/brandontext-medium.ttf
          weight: 500

    - family: digitalClock
      fonts:
        - asset: assets/fonts/DS-DIGI.ttf
          weight: 400